config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, shallow: true
  end

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post, only: [:new, :create]
  before_action :find_comment, only: [:edit, :update, :destroy]

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.new(comment_params)
    if @comment.save
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
  end

  private
  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.all
  end

  def show
    @comments = @post.comments.order(id: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path, notice: "文章新增成功"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "文章已更新"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy

    redirect_to posts_path, notice: "文章已刪除", status: :see_other
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag comment do %>
  <div class="px-2 py-2 my-3 text-gray-800 rounded shadow bg-gray-50">
    <%= link_to "編輯", edit_comment_path(comment) %> |
    <%= link_to "刪除", comment, data: { turbo_method: "delete", turbo_confirm: "刪除留言？" } %>
    <%= comment.content %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment]) do |form| %>
  <div>
    <%= form.text_area :content %>
  </div>
  <%= link_to "Cancel", :back, class: 'px-3 py-2 bg-gray-100 rounded-sm' %>
  <%= form.submit class: 'px-3 py-2 bg-pink-100 rounded-sm' %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend dom_id(@post, :comment) do %>
  <%= render @comment %>
<% end %>

<%= turbo_stream.update "new_comment" do %>
  <%= link_to "新增留言", new_post_comment_path(@post), class: 'px-3 py-2 bg-gray-200 rounded' %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove @comment %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render "form", post: @post, comment: @comment %>
<% end %>

app/views/comments/new.html.erb
<%= turbo_frame_tag "new_comment" do %>
  <%= render "form", post: @post, comment: @comment %>
<% end %>

app/views/comments/update.turbo_stream.erb
<%= turbo_stream.update @comment, @comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.text_area :content, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div>
  <h2 class="text-2xl font-medium">
    <%= link_to post.title, post %>
  </h2>

  <article class="my-5">
    <%= simple_format post.content %>
  </article>
</div>

<% if action_name == "show" %>
  <%= turbo_frame_tag "new_comment" do %>
    <%= link_to "新增留言", new_post_comment_path(post), class: 'px-3 py-2 bg-gray-200 rounded' %>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">更新文章</h1>
  <%= render "form", post: @post %>
</div>

app/views/posts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex items-center justify-between">
    <h1 class="text-4xl font-bold">文章列表</h1>
    <%= link_to '新增', new_post_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <hr class="my-3">
  <div id="posts" class="min-w-full">
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render "form", post: @post %>

  <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<div class="w-full px-3 mx-auto md:w-2/3">
  <div class="mx-auto my-6">
    <% if notice.present? %>
      <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
    <% end %>

    <%= link_to '編輯', edit_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= link_to '刪除', @post, data: {turbo_method: "delete", turbo_confirm: "確認刪除？"}, class: "mt-2 rounded-lg py-3 px-5 bg-red-500 text-red-50 font-medium" %>
    </div>
    <%= render @post %>

  </div>
  <section id="<%= dom_id(@post, :comment) %>">
    <%= render @comments %>
  </section>
</div>